### PR TITLE
Fix sidebar display in site editor + make it more consistent

### LINKED ISSUE #340: Sidebar template part preview
Can we improve a bit the preview of this template part? Should we hide it?

Screenshot 2023-09-12 at 17 47 59

### PR DESCRIPTION
**Pull request by richtabor**
###  Description

Tidies up the sidebar so that the spacing/font sizes are a bit more consistent. And makes the sidebar look nice in the focused template part view. Closes #340.

#### Before: 

CleanShot 2023-09-18 at 14 05 32

#### After: 

CleanShot 2023-09-18 at 14 08 38

### CODE REVIEW

File: patterns/hidden-sidebar.php [hunk 1]
```diff
@@ -6,64 +6,87 @@
...
-<!-- wp:query {"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
-<div class="wp-block-query"><!-- wp:post-template -->
-<!-- wp:group {"style":{"spacing":{"blockGap":"0.5rem"}},"layout":{"type":"flex","orientation":"vertical"}} -->
-<div class="wp-block-group"><!-- wp:post-title {"isLink":true,"fontSize":"medium"} /-->
+	<!-- wp:group {"layout":{"type":"constrained"}} -->
+	<div class="wp-block-group"><!-- wp:group {"style":{"spacing":{"blockGap":"0.3em"}},"layout":{"type":"flex","justifyContent":"left"}} -->
+	<div class="wp-block-group"><!-- wp:post-date {"format":"M j, Y","isLink":true} /-->
 
-<!-- wp:pattern {"slug":"twentytwentyfour/post-meta"} /-->
+	<!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|contrast-2"}}}},"textColor":"contrast-2"} -->
```
Comment (carolinan) [inline patterns/hidden-sidebar.php:46]: Why can't the meta pattern be re-used?

Comment (MaggieCabrera) [reply patterns/hidden-sidebar.php:46]: yes, does it need adjusting?

Comment (richtabor) [reply patterns/hidden-sidebar.php:46]: We need to use a post meta template part. https://github.com/WordPress/twentytwentyfour/issues/409

Comment (richtabor) [reply patterns/hidden-sidebar.php:46]: That's fine to use the pattern for now.

Comment (luminuu) [reply patterns/hidden-sidebar.php:46]: So to merge this PR this part it stays a pattern for now, but afterwards with a new PR it's updated to a template part?

**Review by luminuu — APPROVED** [review]
Let's merge it for now and update the post meta to template part later.
